name: Chalet Uxello
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1311229655984789
title: Chalet Uxello Les Gets
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7694ee'
    - '#aac2fe'
    - '#1a0d1e'
    - '#384789'
    - '#eaf4fc'
  brandStrength: 0
  lightness: 0.623698906507343
  saturation: 0.6625438772607595
  rhythmicContrast: 0.5
purpose: []
