name: Chalet Uxello
favicon: null
layout_spectrum: 0.44990835525095463
typography_spectrum: 0.1311229655984789
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.058815195225179195
  lightness: 0.623698906507343
  saturation: 0.6625438772607595
  rhythmicContrast: 0.7055764293763787
purpose: []
